import React, { Component } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Image,
  StatusBar,
  SafeAreaView,
  TouchableOpacity,
  Alert,
} from 'react-native';
import GradientBackground from '../components/GradientBackground';
import GradientButton from '../components/GradientButton';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons'; // <-- Icon import
import EventDetails from '../api/EventDetails';
import getToken from '../api/getToken';
import RNHTMLtoPDF from 'react-native-html-to-pdf';



class ListTickets extends Component {
  constructor(props) {
    super(props);
    const { eid } = props.route.params;
    this.state = {
      eid: parseInt(eid),       // Set eid directly from route params
      totalTickets: 0,
      soldTickets: 0,
      usedTickets: 0,
      remainingTickets: 0,
      tickets: [],
    };
  }

  async componentDidMount() {
    try {
      const token = await getToken();
      const eventData = await EventDetails(token, this.state.eid);

      if (eventData) {
        this.setState({
          totalTickets: eventData.total_tickets || 0,
          usedTickets: eventData.tickets_checked || 0,
          remainingTickets: eventData.tickets_available || 0,
          soldTickets:
            (eventData.tickets_checked || 0) +
            (eventData.tickets_available || 0),
          tickets: eventData.tickets || [], // <-- store tickets
        });
      }
    } catch (error) {
      console.error('Failed to fetch event ticket data:', error);
    }
  }


  handleBack = () => {
    this.props.navigation.goBack();
  };
  generatePdf = async () => {
    const { title } = this.props.route.params;
    const { soldTickets, usedTickets, remainingTickets, tickets } = this.state;

    const ticketRows = tickets
      .map((ticket, index) => {
        const isChecked = ticket.ticket_status === 'checked';
        const rowStyle = isChecked
          ? 'background-color: #d4edda; color: #155724;' // green for checked
          : 'background-color: #f8d7da; color: #721c24;'; // red for unchecked

        return `
        <tr style="${rowStyle}">
          <td style="border: 1px solid #999; padding: 6px;">${index + 1}</td>
          <td style="border: 1px solid #999; padding: 6px;">${ticket.customer_name}</td>
          <td style="border: 1px solid #999; padding: 6px;">${ticket.email}</td>
          <td style="border: 1px solid #999; padding: 6px;">${ticket.qr_code}</td>
          <td style="border: 1px solid #999; padding: 6px; font-weight: bold;">
            ${ticket.ticket_status || 'Not Checked'}
          </td>
        </tr>`;
      })
      .join('');

    const htmlContent = `
    <div style="font-family: Arial, sans-serif; padding: 20px;">
      <h1 style="text-align:center; color:#333;">${title}</h1>
      <table style="width:100%; font-size:16px; margin-bottom:20px;">
        <tr><td><strong>Sold Tickets:</strong></td><td>${soldTickets}</td></tr>
        <tr><td><strong>Used Tickets:</strong></td><td>${usedTickets}</td></tr>
        <tr><td><strong>Remaining Tickets:</strong></td><td>${remainingTickets}</td></tr>
      </table>

      <h2 style="text-align:center; margin-bottom:10px;">Ticket Details</h2>
      <table style="width:100%; border-collapse: collapse; font-size:14px; margin-bottom:30px;">
        <tr style="background-color: #343a40; color: #fff;">
          <th style="border: 1px solid #999; padding: 6px;">#</th>
          <th style="border: 1px solid #999; padding: 6px;">Name</th>
          <th style="border: 1px solid #999; padding: 6px;">Email</th>
          <th style="border: 1px solid #999; padding: 6px;">QR Code</th>
          <th style="border: 1px solid #999; padding: 6px;">Status</th>
        </tr>
        ${ticketRows}
      </table>

      <footer style="text-align: center; font-size: 12px; color: #888; border-top: 1px solid #ccc; padding-top: 10px;">
        Generated by <strong>TicketWave</strong> &mdash; Simplifying Event Entry
      </footer>
    </div>
  `;

    try {
      const options = {
        html: htmlContent,
        fileName: `TicketStats_${Date.now()}`,
        directory: 'Download',
      };

      const file = await RNHTMLtoPDF.convert(options);
      Alert.alert('Success', `PDF saved to:\n${file.filePath}`);
      console.log('PDF generated at:', file.filePath);
    } catch (error) {
      console.error('PDF generation error:', error);
      Alert.alert('Error', 'Failed to generate PDF.');
    }
  };



  render() {
    const { title } = this.props.route.params;

    return (
      <>
        <StatusBar
          translucent
          backgroundColor="transparent"
          barStyle="light-content"
        />
        <GradientBackground>
          <SafeAreaView style={styles.safe}>
            <View style={styles.header}>
              <TouchableOpacity onPress={this.handleBack}>
                <View style={styles.backContent}>
                  <Image
                    source={require('../assets/back.png')}
                    style={styles.backIcon}
                    resizeMode="contain"
                  />
                  <Text style={styles.backText}>Events</Text>
                </View>
              </TouchableOpacity>
            </View>

            <Text style={styles.title}>{title}</Text>
            <View style={styles.spacer} />

            {/* Event details section */}
            <View style={styles.detailsBox}>
              <View style={styles.detailRow}>
                <Text style={styles.detailLabel}>Sold Tickets</Text>
                <Text style={styles.detailValue}>{this.state.soldTickets}</Text>
              </View>
              <View style={styles.detailRow}>
                <Text style={styles.detailLabel}>Used Tickets</Text>
                <Text style={styles.detailValue}>{this.state.usedTickets}</Text>
              </View>
              <View style={styles.detailRow}>
                <Text style={styles.detailLabel}>Remaining Tickets</Text>
                <Text style={styles.detailValue}>{this.state.remainingTickets}</Text>
              </View>

              {/* <View style={styles.detailRow}>
                <Text style={styles.detailLabel}>Selected Time</Text>

              </View>
              <View style={styles.detailRow}>
                <Text style={styles.detailLabel}>From</Text>
                <View style={styles.dateRow}>
                  <Text style={styles.detailValue}>2025-07-15</Text>
                  <Icon
                    name="calendar-month"
                    size={20}
                    color="#FF71D2"
                    style={styles.iconMargin}
                  />
                </View>
              </View>
              <View style={styles.detailRow}>
                <Text style={styles.detailLabel}>To</Text>
                <View style={styles.dateRow}>
                  <Text style={styles.detailValue}>2025-07-16</Text>
                  <Icon
                    name="calendar-month"
                    size={20}
                    color="#FF71D2"
                    style={styles.iconMargin}
                  />
                </View>
              </View> */}
              <View style={styles.pdfbutton}>
                <GradientButton
                  text={
                    <View style={styles.pdfContent}>
                      <Icon
                        name="file-pdf-box"
                        size={26}
                        color="#fff"
                        style={styles.iconMargin}
                      />
                      <Text style={styles.pdfText}>Generate PDF</Text>
                    </View>
                  }
                  onPress={this.generatePdf}
                />
              </View>
            </View>
            <GradientButton
              text={
                <View style={styles.scanContent}>
                  <Image
                    source={require('../assets/oHistory.png')}
                    style={styles.historyIcon}
                  />
                  <Text style={styles.scanText}>History</Text>
                </View>
              }
              style={styles.historyBtn}
              onPress={() =>
                this.props.navigation.navigate('History', {
                  eid: this.state.eid,
                })
              }
            />

            {/* Scan Button */}
            <GradientButton
              text={
                <View style={styles.scanContent}>
                  <Image
                    source={require('../assets/scannericon.png')}
                    style={styles.scanIcon}
                  />
                  <Text style={styles.scanText}>Scan</Text>
                </View>
              }
              onPress={() =>
                this.props.navigation.navigate('ScanBarcode', {
                  eid: this.state.eid,
                })
              }
              style={styles.scanBtn}
              textStyle={styles.btnTextWrap}
            />
          </SafeAreaView>
        </GradientBackground>
      </>
    );
  }
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: -50,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'left',
    marginTop: 10,
    paddingHorizontal: 10,
  },
  backContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backText: {
    fontSize: 25,
    color: '#FF71D2',
    marginLeft: -30,
    fontWeight: '500',
  },
  spacer: {
    marginVertical: 10,
  },
  detailsBox: {
    backgroundColor: '#4f4f4f', // ash color
    borderRadius: 10,
    padding: 15,
    marginVertical: 20,
    marginBottom: 80,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 5,
  },
  detailLabel: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '500',
  },
  detailValue: {
    fontSize: 16,
    color: '#fff',
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconMargin: {
    marginLeft: 8,
  },
  pdfContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pdfText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  pdfbutton: {
    marginTop: 25,
    marginBottom: 15,
  },
  scanBtn: {
    paddingHorizontal: 40,
    paddingVertical: 12,
    borderRadius: 10,
    alignSelf: 'center',
    minWidth: 200,
    minHeight: 70,
    marginBottom: 150,
    marginTop: 30,
  },
  historyBtn: {
    paddingHorizontal: 40,
    paddingVertical: 12,
    borderRadius: 10,
    alignSelf: 'center',
    minWidth: 200,
    minHeight: 70,
    marginBottom: 20,
  },
  scanContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  scanIcon: {
    width: 40,
    height: 40,
    marginRight: 10,
    tintColor: '#fff',
  },
  historyIcon: {
    width: 40,
    height: 40,
    marginRight: 10,
  },
  scanText: {
    fontSize: 25,
    fontWeight: '600',
    color: '#fff',
  },
  btnTextWrap: {
    paddingHorizontal: 0,
  },
});

export default ListTickets;
